apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-ilab13
  janus-idp.io/tekton: test-ilab13
  backstage.io/kubernetes-id: test-ilab13
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test-ilab13
resources:
- initialize-namespace.yaml
- pvc.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml